default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: <%= ENV['DB_IP'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV["DB_PASS"] %>
  database: employee_attendance

test:
  <<: *default
  database: employee_attendance_test

# production:
#   <<: *default
#   database: employee_attendance
production:
  <<: *default
  database: <%= ENV['HEROKU_DATABASE'] %>
  username: <%= ENV['HEROKU_USER'] %>
  password: <%= ENV['HEROKU_DATABASE_PASSWORD'] %>

