default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_IP'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV["DB_PASS"] %>
  pool: 5

development:
  <<: *default
  database: employee_attendance

test:
  <<: *default
  database: employee_attendance_test

production:
  <<: *default
  database: employee_attendance

