default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: employee_attendance
  host: 45.34.14.127
  # <%= ENV['db_host_ip'] %>
  username: 'deepesh'
  # <%= ENV['db_username'] %>
  password: 'Make@246'
  # <%= ENV['db_password'] %>

test:
  <<: *default
  database: employee_attendance_test

# production:
#   <<: *default
#   database: employee_attendance
# for heroku only
production:
  <<: *default
  database: employee_attendance
  host: 45.34.14.127
  # <%= ENV['db_host_ip'] %>
  username: 'deepesh'
  # <%= ENV['db_username'] %>
  password: 'Make@246'
  # <%= ENV['db_password'] %>

  # database: <%= ENV['HEROKU_DATABASE'] %>
  # username: <%= ENV['HEROKU_USER'] %>
  # password: <%= ENV['HEROKU_DATABASE_PASSWORD'] %>

